### PR TITLE
Fix modal formatting

### LINKED ISSUE #2288: Correct demo modal styling
The current layout and styling of the modal that allows users to select their demo experience does not exactly match our [designs](https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?node-id=2923-12508&m=dev). Let's bring out implementation of this component into alignment with the designs.

### PR DESCRIPTION
**Pull request by DanPaseltiner**
# PULL REQUEST

## Summary
This PR updates styling and layout for the modal. Additionally, we manually apply focus styling in order to support Safari. In the future we should probably expand this solution beyond just the modal. The next button on the modal is now always disabled until the user makes a selection. Finally, there were some issues with phone number auto population when a user would change their selection from a demo patient with a phone number to one without or vice versa.

## Related Issue
Fixes #2288 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

File: containers/tefca-viewer/src/app/page.tsx [hunk 1]
```diff
@@ -37,6 +37,16 @@ export default function LandingPage() {
...
+    document.getElementById(option)?.focus();
+  };
+
+  const modalOptions = {
+    chlamydia: "Chlamydia case investigation",
+    gonorrhea: "Gonorrhea case investigation",
+    syphilis: "Syphilis case investigation",
+    cancer: "Cancer case investigation",
+    "newborn-screening": "Newborn screening follow-up",
+    "social-determinants": "Gather social determinants of health for a patient",
```
Comment (m-goggins) [inline containers/tefca-viewer/src/app/page.tsx:49]: We have a very similar const in `constants.ts` called `demoQueryOptions` that I think we should try to re-use instead of redefining here. Or if that doesn't work, I would move modalOptions to the `constants.ts` file.

File: containers/tefca-viewer/src/app/page.tsx [hunk 2]
```diff
@@ -133,70 +144,35 @@ export default function LandingPage() {
...
+              {Object.keys(modalOptions).map((option) => (
+                <Button
+                  type="button"
+                  className={`modal-option ${
+                    selectedOption === option ? "selected" : ""
+                  }`}
+                  id={option}
+                  onClick={() => handleOptionClick(option)}
+                >
+                  {modalOptions[option as keyof typeof modalOptions]}
```
Comment (m-goggins) [inline containers/tefca-viewer/src/app/page.tsx:165]: nice!

File: containers/tefca-viewer/src/app/constants.ts [hunk 3]
```diff
@@ -65,6 +65,7 @@ export const demoData: Record<PatientType, DemoDataFields> = {
     LastName: "JMC",
     DOB: "2001-05-07",
     MRN: "b50z-wayszq-ofib",
+    Phone: "",
```
Comment (m-goggins) [inline containers/tefca-viewer/src/app/constants.ts:68]: We could add this as another ticket, but I think a more robust solution would be to change `fillFields` to reset fields before setting with new data (or something like that).

**Review by m-goggins — COMMENTED** [review]
Looks pretty good to me! The selection looks sweet. Just had a couple of comments about filling the fields and moving constants to another spot or reusing constants that already exist.

File: containers/tefca-viewer/src/app/page.tsx (hunk 1 above)
Comment (DanPaseltiner) [reply containers/tefca-viewer/src/app/page.tsx:49]: Yeah, I looked at trying to reuse `demoQueryOptions`, but the problem is that for the UI designs we need this specific copy. I'm open to suggestions, but can definitely move into `constants.ts`.

**Review by lg-king — APPROVED** [review]

**Review by robertandremitchell — APPROVED** [review]
looks good. minor quibble I don't know if it matters: if you click on one of the modal boxes, it does highlight in blue. however, if you then click elsewhere, it does seem to remember your selection, but loses the blue highlight. not sure if it should retain the blue highlight; it does appear to retain the lighter blue font.

File: containers/tefca-viewer/src/app/constants.ts (hunk 3 above)
Comment (bamader) [reply containers/tefca-viewer/src/app/constants.ts:68]: Yeah very firm agree here. This is also making e2e tests somewhat wonky depending on the use case we're testing. I would be okay with making it a separate ticket.

File: containers/tefca-viewer/src/app/page.tsx (hunk 1 above)
Comment (bamader) [reply containers/tefca-viewer/src/app/page.tsx:49]: If we have to have this specific copy I would move to `constants.ts`

**Review by bamader — COMMENTED** [review]
Overall looks solid, just some thoughts around the constants file and the field clearing

File: containers/tefca-viewer/src/app/page.tsx (hunk 1 above)
Comment (m-goggins) [reply containers/tefca-viewer/src/app/page.tsx:49]: Maybe this is an opportunity to standardize the copy across different places?

Comment (bamader) [reply containers/tefca-viewer/src/app/page.tsx:49]: Would love that tbh. Too many variations of `chlamydia` `chlamydia-sti` `chlamydia-sti-positive` etc. 😅

Comment (DanPaseltiner) [reply containers/tefca-viewer/src/app/page.tsx]: I have moved to constants. I think a large effort to improve copy consistency should wait for another ticket as it requires coordination with design

File: containers/tefca-viewer/src/app/constants.ts (hunk 3 above)
Comment (DanPaseltiner) [reply containers/tefca-viewer/src/app/constants.ts:81]: Let's address this in another ticket if needed. I believe a "reset" in this context is simply setting the value to an empty string which is what the current solution already does. I could very well be missing something here, but I don't much value in a dedicated reset step. I'm going to merge as is and we can discuss next week when we are all back in the office if a follow up ticket here is required.
