### PR TITLE
fix: add time to meds and procedures

### LINKED ISSUE #2774: BUG: Times not showing up in certain date/time fields
## Description

Across several fields (listed below), there are examples in which times aren't showing up in a date/time value even when the information is available.

Affected fields (from examples):
- Active Problem onset date/time
- Administered Medication start date/time
- Procedures date/time performed.

Please investigate the issues below and make any necessary changes so that these fields also display the dates (and any relevant time zones, if info is available) in the Viewer.

Potential solution: This may be as simple as making sure we're using the `formatDateTime` function instead of `formatDate` for these fields?

## Steps to reproduce

Example eCRs:
- 7f02b35a-b172-4845-af55-d173574e5579: [When times are available, times aren’t showing up in Active Problem onset date](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725805571119)
- ffa9550f-9a88-4348-9da3-4ca4a1e5f554: [Active Problem dates not showing times if available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724871024283479)
- 3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382: [When times are available, times aren’t showing up in Active Problem onset date](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724102163133399)
- 3a6febc6-cc0f-4706-8322-da0cd16bb7c6: [Not displaying Medication Start times if available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1723840913496029)
- TN_sample eCR2: [Administered medications times is not displayed when info is available](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724877604812499)
- 12aa8d10-c131-44f6-9a34-5873d2148084: [Medication start date doesn't display time](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1723832602137879)
- 10e5b07b-5d3f-426f-a7e1-13ea909ff5a5: [Procedures "Date Performed" doesn't display times when available](https://skylight-hq.slack.com/files/U05J6B6RZFV/F07HP5Q883S/4.png)

## Expected Result

If times are available, then they (and any available timezone information) should be displayed in Date fields in the eCR Viewer.

## Actual result

Example from `7f02b35a-b172-4845-af55-d173574e5579`:

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by mcmcgrath13**
# PULL REQUEST

## Summary
Sometimes a time is included with problem list, medication, and procedures. Allow it to be rendered.

## Related Issue
Fixes #2774

## Additional Information
image

image
image

### CODE REVIEW

File: containers/ecr-viewer/src/app/view-data/components/common.tsx [hunk 1]
```diff
@@ -210,7 +210,7 @@ export const returnProblemsTable = (
       columnName: "Active Problem",
       infoPath: "activeProblemsDisplay",
     },
-    { columnName: "Onset Date", infoPath: "activeProblemsOnsetDate" },
+    { columnName: "Onset Date/Time", infoPath: "activeProblemsOnsetDate" },
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/view-data/components/common.tsx:213]: Same here (comment above)

File: containers/ecr-viewer/src/app/view-data/components/common.tsx [hunk 2]
```diff
@@ -345,12 +345,12 @@ export const returnProceduresTable = (
 
   const columnInfo: ColumnInfoInput[] = [
     { columnName: "Name", infoPath: "procedureName" },
-    { columnName: "Date Performed", infoPath: "procedureDate" },
+    { columnName: "Date/Time Performed", infoPath: "procedureDate" },
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/view-data/components/common.tsx:348]: Same here (comment above)

File: containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx [hunk 3]
```diff
@@ -28,13 +28,16 @@ export const AdministeredMedication = ({
 
   const headers = BuildHeaders([
     { columnName: "Medication Name", className: "bg-gray-5 minw-15" },
-    { columnName: "Medication Start Date", className: "bg-gray-5 minw-15" },
+    {
+      columnName: "Medication Start Date/Time",
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx:32]: Just double checking that this has already been okay'ed by Ashton? Didn't see this change in the Figma designs

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx:32]: I followed the convention of other fields that had DateTimes instead of Dates. @ashton-skylight would you prefer this stay saying `Date` even though we now return time when available?

**Comment by ashton-skylight** [comment]
Thanks Mary! Is it possible to move time to the second line?
Screenshot 2024-11-22 at 4 00 47 PM

File: containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx (hunk 3 above)
Comment (ashton-skylight) [reply containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx:32]: Looks good! Let's go with Date/Time @mcmcgrath13

Comment (ashton-skylight) [reply containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx:32]: @angelathe Thanks for checking! The Figma isn't updated. Will try to do that the week following Thanksgiving

**Comment by mcmcgrath13** [comment]
> Thanks Mary! Is it possible to move time to the second line? Screenshot 2024-11-22 at 4 00 47 PM

@ashton-skylight across the board? or just in the procedure table?

**Comment by mcmcgrath13** [comment]
> @mcmcgrath13 Just for the procedures table

all set
image
