### PR TITLE
fix: display all tables related to treatment plan

### LINKED ISSUE #2746: BUG: Pending Results is not displayed
## Description

For the eCRs below, the Pending Results information is not being converted to FHIR and displayed in the eCR Viewer. Please fix the FHIR conversion process for this section and ensure that it is displayed in the eCR Viewer.

## Steps to reproduce

Example eCRs:
- `3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382`: [Plan of Treatment (Pending result) isn’t displayed in the eCR Viewer](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724102690823459)
- `7f02b35a-b172-4845-af55-d173574e5579`: [Plan of Treatment is not displaying available Pending Results (”Pending Tests”)](https://skylight-hq.slack.com/archives/C07DX0PCCSJ/p1724725925433779)

## Expected Result

If pending result information is available, it should be displayed in the eCR Viewer under the Pending Results sub-section of the Plan of Treatment (Clinical Info section).

## Actual result

Example from `3e0d3f9b-4b26-47d2-9ddd-3ac4d7045382`:

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [x] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

FHIR conversion will be required for this ticket.

### PR DESCRIPTION
**Pull request by mcmcgrath13**
# PULL REQUEST

## Summary
Allow for more treatment plan data to be displayed in the eCR viewer.

* Use updated FHIR-Converter which preserves the contents of `<text>` nodes as `_innerText` and return this for the `div` of a composition instead of trying to rebuild the html from the jsonified parsed xml (which doesn't preserve order).
* Allow more formats to be handled by `formatTablesToJSON` to account for the examples we have
* Instead of looking for specific plan of treatment headers and table values, take all headers which have table data and present them to the user with the column names that were provided in the eCR

## Related Issue
Fixes #2746

## Additional Information

* Because we've changed how the eCR is parsed, in cases where a composition ID wasn't present in the text file, the composition ID (which is used as the primary key in our db) *will change*
  * I've stabilized how this is generated so in the future it won't be sensitive to parsing changes

Screenshots:
image
image
image

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

File: containers/fhir-converter/Dockerfile [hunk 1]
```diff
@@ -1,7 +1,7 @@
 FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
 
 # Download FHIR-Converter
-RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-1 --single-branch /build/FHIR-Converter
+RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch mcm/add-inner-text --single-branch /build/FHIR-Converter
```
Comment (mcmcgrath13) [inline containers/fhir-converter/Dockerfile:4]: TODO: don't merge PR until this can point to a release tag

File: containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
Comment (austin-hall-skylight) [inline containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx:1]: Thanks for slipping this fix in here.

**Review by austin-hall-skylight — APPROVED** [review]
