### PR TITLE
fix: don't display "Lab Interpretation" component

### LINKED ISSUE #2953: `Lab Interpretation` should not be displayed in the Diagnostic Report table
## Description

- `Lab Interpretation` should not be displayed in the Diagnostic Report Data

## Steps to reproduce

1. Visit http://localhost:3000/view-data?id=1.2.840.114350.1.13.461.2.7.8.688883.134375046
2. Scroll to Lab Results from the BARONESS LAB
3. Expand the PTT accordion

## Expected
Lab Interpretation is not in the table, but still appears in the header when abnormal

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by mcmcgrath13**
# PULL REQUEST

## Summary
Filter out diagnostic lab components whose name is "Lab Interpretation".

This feels a bit hacky, but I didn't quickly see a better way. Suggestions very welcome.

## Related Issue
Fixes #2953

## Additional Information
image

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

File: containers/ecr-viewer/src/app/services/labsService.tsx [hunk 1]
```diff
@@ -332,7 +332,11 @@ export function evaluateObservationTable(
   ).filter(
     (observation) =>
       !observation.component &&
-      observation.code?.coding.some((c: Coding) => c?.display),
+      // Make sure there is a component name, but it isn't "Lab Interpretation" as that's handled
+      // via the tab on the result's name
+      observation.code?.coding.some(
+        (c: Coding) => c?.display && c?.display !== "Lab Interpretation",
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/services/labsService.tsx:338]: Hm, another option is using the LOINC code (`56850-1`) instead of the display, but I don't think that's any better

https://loinc.org/56850-1

File: containers/ecr-viewer/src/app/tests/assets/BundleLab.json [hunk 2]
```diff
@@ -396,6 +403,77 @@
...
+              },
+              {
+                "url": "observation entry reference value",
+                "valueString": "#Result.1.2.840.114350.1.13.297.3.7.2.798268.1670844.Comp1"
+              }
+            ]
+          }
+        ],
+        "subject": {
+          "reference": "Patient/cfbe36e2-a7ef-476e-8b28-02912388abe9"
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/tests/assets/BundleLab.json:469]: Patient ID should probably reference the ID in the Patient resource above : `1586f68b-1a17-4188-ac0b-82c3cbdbfbda`

File: containers/ecr-viewer/src/app/tests/assets/BundleLab.json [hunk 3]
```diff
@@ -396,6 +403,77 @@
...
+                "valueDateTime": "2022-09-28T20:51:00Z"
+              },
+              {
+                "url": "specimen receive time",
+                "valueDateTime": "2022-09-28T20:51:36Z"
+              },
+              {
+                "url": "observation entry reference value",
+                "valueString": "#Result.1.2.840.114350.1.13.297.3.7.2.798268.1670844.Comp1"
+              }
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/tests/assets/BundleLab.json:464]: I don't think we need this / examples of Lab Interpretation observations don't usually have an obs entry ref value? Also, the ID already references a different value in the HTML string (Line 50)

**Review by angelathe — COMMENTED** [review]
Looks good! Just a few nits

File: containers/ecr-viewer/src/app/tests/assets/BundleLab.json (hunk 3 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/tests/assets/BundleLab.json:464]: I had copied one from the wild, but given that this doesn't point to anything sensical, agreed on deleting

**Review by angelathe — APPROVED** [review]
