### PR TITLE
Fix accessibility issue with lab result accordion headers

### LINKED ISSUE #2421: Lab results included in Condition Summary section fail accessibility tests
## Description

Lighthouse tests are failing because lab result headers are 2 sizes larger than the condition summary header.

## Steps to reproduce
View [this ecr summary](http://localhost:3000/view-data?id=1.2.840.114350.1.13.297.3.7.8.688883.567479#ecr-summary) and run lighthouse accessibility tests.

## Expected Result

Tests pass with no audit errors.

## Actual result

I get the error 
`Heading elements are not in a sequentially-descending order`

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

### PR DESCRIPTION
**Pull request by austin-hall-skylight**
# PULL REQUEST

## Summary
Change lab result accordion headers from h5 to h2 to fix accessibility issues (this doesn't change the way they look).

## Related Issue
Fixes #2421 

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by BobanL — COMMENTED** [review]
Although this does fix the issue of accessibility, I think we want to keep the structure of the [heading orders](https://www.med.unc.edu/webguide/accessibility/headings/#:~:text=eu%20lectus%20sapien.-,Screen%20Readers,-HTML%20headings%20serve). 

For example all of the lab info labs should be H5 as they belong to that H4`Lab Results from HOAG MEMORIAL HOSPITAL`. I don't think they really stand on their own.
image
image

Similarly, the issue with the `Condition Summary` section. Each lab in that section logically fits under the `Condition Summary` header which is an h3.  
image

Happy to pair with you if you need anything!

File: containers/ecr-viewer/src/app/view-data/components/AccordionLabResults.tsx [hunk 1]
```diff
@@ -43,7 +46,7 @@ export const AccordionLabResults: React.FC<AccordionLabResultsProps> = ({
           content: content,
           expanded: collapsedByDefault,
           id: title,
-          headingLevel: "h5",
+          headingLevel,
           className: `acc_item_${organizationId}`,
```
Comment (BobanL) [inline containers/ecr-viewer/src/app/view-data/components/AccordionLabResults.tsx:50]: Seems like the side nav is picking up the labs [because it's not an h5 anymore](https://github.com/CDCgov/phdi/blob/a411f8365535f4427a278766d60f4f05798d1154/containers/ecr-viewer/src/app/view-data/components/SideNav.tsx#L35). If you just add `side-nav-ignore` to this class name it should be resolved since  no lab results should be in the sidenav anyways.
image
```suggestion
          className: `acc_item_${organizationId} side-nav-ignore`,
```

**Review by BobanL — APPROVED** [review]
Thanks for making those changes and fixing this issue!
