### PR TITLE
Fix duplicate postgres database connection issue

### LINKED ISSUE #2813: Duplicate database connection in eCR Viewer
## Description

- Duplicate eCR viewer database connections are being made

## Steps to reproduce

1.  Run or build eCR Viewer

## Expected Result

- No warnings should appear

## Actual result

- Warning about duplicate database connections being made
image

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- Likely will have to be made into a [singleton](https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise#:~:text=root%20after%20initialization-,UPDATE%2D2,-Some%20developers%20have).

### PR DESCRIPTION
**Pull request by gordonfarrell**
# PULL REQUEST

## Summary
Refactors the way we setup and use pgPromise to eliminate the duplicate database connection issue. The db connection is now set up as a singleton and exported everywhere rather than pulling it in and setting things up in each individual file that needs to access it

## Related Issue
Fixes #2813

## Acceptance Criteria
- No longer see the following message in the eCR viewer logs
image

### CODE REVIEW

File: containers/ecr-viewer/src/app/api/services/postgres_db.ts [hunk 1]
```diff
@@ -1,4 +1,41 @@
...
-export const database = pgp()(db_url);
+/**
+ * Global scope singleton creator for pgPromise
+ * @async
+ * @function createSingleton
+ * @param name A name for your singleton
+ * @param create Anonymous function containing what you want singleton-ized
+ * @returns A singleton of the provided object
+ */
+export const createSingleton = <T>(name: string, create: () => T): T => {
```
Comment (austin-hall-skylight) [inline containers/ecr-viewer/src/app/api/services/postgres_db.ts:11]: Nitpick but this doesn't need to be exported.

**Review by austin-hall-skylight — CHANGES_REQUESTED** [review]

File: containers/ecr-viewer/src/app/api/services/postgres_db.ts (hunk 1 above)
Comment (gordonfarrell) [reply containers/ecr-viewer/src/app/api/services/postgres_db.ts:11]: Oh nice catch!

**Review by austin-hall-skylight — APPROVED** [review]
